{{- if .Values.secrets.enabled }}
{{- if or .Values.secrets.toEnvs .Values.secrets.toFiles }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cronjob.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - find:
      tags:
        {{ include "cronjob.fullname" . }}: "true"
{{- end }}
---
{{- if .Values.secrets.toEnvironments }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cronjob.fullname" . }}-secrets-env
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
{{- range .Values.secrets.toEnvironments }}
  - extract:
      key: {{ .name | quote }}
{{- end }}
{{- end }} # if .Values.secrets.toEnvironments
{{- end }} # if .Values.secrets.enabled
