{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cronjob.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - find:
      tags:
        {{ include "cronjob.fullname" . }}: "true"
{{- range .Values.secrets.toFiles }}
  - find:
      name:
        regexp: {{ .name | quote }}
{{- end }}
{{- range .Values.secrets.toEnvironments}}
  - find:
      name:
        regexp: {{ .name | quote }}
{{- end }}
{{- end }}
