apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-stateful.fullname" . }}
  labels:
    {{- include "app-stateful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.serviceMonitor.enabled }}
    - port: {{ .Values.serviceMonitor.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end}}
  selector:
    {{- include "app-stateful.selectorLabels" . | nindent 4 }}
