apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  CONFIG_KEY: "config-value"
  CONFIG_KEY2: "config-value2"
  DATABASE_HOST: db.example.com
  DATABASE_PORT: "5432"
  DATABASE_USER: myuser
  DATABASE_PASSWORD: mypassword

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap2
data:
  key1: value1
  key2: value2
