{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  target:
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
  dataFrom:
  - find:
      tags:
        {{ include "app.fullname" . }}: "true"
{{- end }}
